name: CI
on: [push, pull_request]

jobs:
  test:
    name: Test
    strategy:
      matrix:
        go: ['1.15', '1.16', '1.17', '1.18', '1.19']
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go }}
        stable: false
    - name: Test
      run: go vet . && go build . && go test -count=1 -covermode=count -coverprofile=coverage.out .
